language: smalltalk


os:
    - linux


smalltalk:
    - Pharo-6.1

env:
  matrix:
    - JOB=test TYPE=System ARCHETYPE=book OUTPUT=html
    - JOB=test TYPE=System ARCHETYPE=book OUTPUT=pdf

install:
    # Pillar installation
    - git clone https://github.com/samakhov/pillar.git .pillar -b merge/archetypes # Clone pillar
    - cd .pillar && ./scripts/build.sh && cd ..

script:
    - .pillar/build/pillar build html
    - cd _result/html && touch .nojekyll && cd ..

deploy:
   provider: pages
   skip-cleanup: true
   github-token: $GH_TOKEN
   keep-history: true
   local_dir: _result/html
   on:
     branch: master
